track_parcel:
  fields:
    tracking_code:
      required: true
      selector:
        text:
    country:
      default: PL
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      selector:
        text:
    country:
      default: PL
      selector:
        text:
